name:   "z slack Notify"

on:
    workflow_dispatch:

jobs:
    notify:
        name:   Slack notify
        runs-on:    ubuntu-latest
        steps:
            -   name:   Slack notify
                uses:   slackapi/slack-github-action@v1.24.0
                with:
                    channel-id: 'C067X2VLEVD'
                    payload:    |
                        {
                            "attachments": [
                                {
                                    "blocks": [
                                        {
                                            "type": "section",
                                            "text": {
                                                "type": "mrkdwn",
                                                "text": "hello"
                                            }
                                        },
                                        {
                                            "type": "header",
                                            "text": {
                                                "type": "plain_text",
                                                "text": "Message Header",
                                                "emoji": true
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                env:
                    SLACK_BOT_TOKEN:    ${{ secrets.SLACK_BOT_TOKEN }}