name:   "z slack Notify"

on:
    workflow_dispatch:

jobs:
    notify:
        name:   Slack notify
        runs-on:    ubuntu-latest
        steps:
            -   name:   Slack notify
                uses:   slackapi/slack-github-action@v1.24.0
                with:
                    channel-id: 'C067X2VLEVD'
                    payload:    |
                        {
                            {
                                "attachments": [
                                    {
                                        "blocks": [
                                            {
                                                "type": "section",
                                                "text": {
                                                    "type": "mrkdwn",
                                                    "text": "This is a mrkdwn section block :ghost: *this is bold*, and ~this is crossed out~, and <https://google.com|this is a link>"
                                                }
                                            },
                                            {
                                                "type": "header",
                                                "text": {
                                                    "type": "plain_text",
                                                    "text": "Message Header",
                                                    "emoji": true
                                                }
                                            }
                                        ]
                                    }
                                ]
                            }
                        }
                env:
                    SLACK_BOT_TOKEN:    ${{ secrets.SLACK_BOT_TOKEN }}